language: node_js
node_js:
- 10.12
before_script:
- node make.js build
before_deploy:
- node make.js after_build
deploy:
  provider: npm
  email: wparad@gmail.com
  api_key:
    secure: ZTwkKtd7ZkyccsIjzjQ9b6y37r5dlkuROx30fhhMmPurhg6E32IrCsDm5b87HxV9dYJCm0MAMB8RtDW/YQ/Bo9h48pAvGV5E1rG48h57R6rEIPGERZ0dakmlFOjt+dlaEb0C4Fv90uWT2Rg2SFS0Lob9pPsNlYvPMGoaHFEwulSCrKjEromo6adB2geAvNVwtp76Ls0IfDwinoQTMsf0/19lf0pWGPWPvfwScE0BZv5ZMVanUKBXBqV8Ipes2c0iZR2WoAOBG7u1y4tk2WSADCLCo9p2jOXCGG55JwpRfvaokjZveM4O2qfXr6BaiDiy8FaXCBpln1K6iLThniPDxE3EpcBr9aLrnPj78tImkgvRqPhNnfgfpizl6Gv6qxHJavhiPnXvi+em/NeLLF8pYPH/GRKYqdOIfp/Fyez4de80k+LhNyYiYCt18hvFOib5PYngXvcsrDM69/n4lLqvlx6yU1taAaPMWUYXHj8jT4hQTCN+z5YdVTRgvuDUdswyfqvuHfJ2CCWE9nm3i46BAkCQXDDB199qqjSiKHu2jIr4tz77iXE3StoL1ePkQofTPcawe7pSlNqj2x8qydnlaGqg3ZuZJMm9zsGzgTQRjXxrcCmSX0QShFqHTJR1VFFB89PUEthgsiKPdp94pIH+a0EIw1NQNm9A4pQY47IepN4=
  skip_cleanup: true
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH != master"
branches:
  only:
  - master
  - "/^release.*/"
env:
  global:
  - secure: Uk/Id3Lxb4YVmtLx/Su+upgnp9Cc1adhI6LIT0MC12jd0XmSb5mnFKI6zzXWNiyZr6/6PFbaiYcGwUPBFRknhhr14O2kt+j9U5KXZvbdiKbl01+6gXBKiJ2SEVnxeIuibmrxEiqSAQlWUpyph/gdOKIvh8bxGzm15jg5n1A58sgJ3cEZc+aVVeZCPD11RespnWRGf2oyVQEyvt+k2KMFWB9UKuGIf4oLfz9IkD/OV5CIpJFkuPnYY+Lnt1zaTTuB1mZ2aY9bqzj6B/lQNsB4jcQxKDtABjLZhZ42yodrHl4HSiiY5odM4cVw4vIPjMgOsDyXbmiKQ5zr1IZVRIqdCRCH496Fcp5LW7db/idPcndsrENNd7d9FD93LTv5LDZfLRbXBU1wjJTnKmPOPFO1xSu5uYs+ekpeilG8gTdgEw+2t1Ew2ZPBRXWskYPzsp0d8dd3dDi438F38D+x1yFQraFYLb2HsT/I6uqZsJQ+OGtvotxF7oLO13JVywaBrkmDFVCggFseSH2G5OJ3FDtsY1FSVfa76x9OKGC6zP3fwOEa5HKVwK9TBTGGLOsNvxp01p6a2Iq4Kc/Gm/1F+CYpDVafObDmgQNGhPdLfBZNIR2GnnVijiazpYbD0Tsa2AP/P/U+ZPOGjZOz/PwHY3xutcX16Z0UpK5vVnGbJ8B3hJo=
